[tool.poetry]
name = "relational database"
version = "0.1.0"
description = ""
authors = ["BuDi4ka <dddd09399@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
